export const GET_AVAILABILITY_REMOTE = 'GET_AVAILABILITY_REMOTE';
export const POST_AVAILABILITY_REMOTE = 'POST_AVAILABILITY_REMOTE';
export const PATCH_AVAILABILITY_REMOTE = 'PATCH_AVAILABILITY_REMOTE';
