export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const GET_MIGRATED_USER_DATA = 'GET_MIGRATED_USER_DATA';
export const GET_USER_PROFILE_PICTURE = 'GET_USER_PROFILE_PICTURE';
