name: Deploy to Next Env.

on:
  pull_request:
    types: [closed]
    branches: [next]

jobs:
  send_ir_mail:
    name: Send IR Email
    runs-on: ubuntu-latest
    environment: NEXT
    if: github.event.pull_request.merged == true
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ github.event.pull_request.title }}
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ vars.EMAIL_SENDER }}
          html_body: ${{ github.event.pull_request.body }}
          ignore_cert: true
          convert_markdown: true
          attachments: attachments.zip,git.diff,./dist/static/*.js
          priority: low
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
