name: Deploy to Prod

concurrency:
  group: PROD
  cancel-in-progress: true

on:
  pull_request:
    types: [closed]
    branches: [prod]

jobs:
  get_ir_label:
    name: Get IR Label
    runs-on: ubuntu-latest
    outputs:
      IR_LABEL: ${{ steps.irLabel.outputs.IR_LABEL }}
    steps:
      - name: Get IR Label
        id: irLabel
        run: |
          echo "IR_LABEL=$(echo '${{ github.event.pull_request.title }}' | grep -o -E 'IR-[0-9]+' | sed -n 1p)" >> $GITHUB_OUTPUT

  deploy_to_prod:
    name: Deploy To Prod
    uses: ./.github/workflows/setup_project.yml
    needs: get_ir_label
    if: github.event.pull_request.merged == true
    with:
      BRANCH: ${{ github.event.pull_request.base.ref }}
      DEPLOY: true
      ENVIRONMENT: PROD
    secrets: inherit

  watch_for_deploy_status:
    name: Watch For Deployment Status
    uses: ./.github/workflows/watch_workflow_steps_status.yml
    needs: get_ir_label
    with:
      JOB_NAME: Deploy To Prod / Setup Project
      STEP_NAME: Deploy
      TYPE: DEPLOYMENT
      IR_LABEL: ${{ needs.get_ir_label.outputs.IR_LABEL }}
      BRANCH: ${{ github.event.pull_request.base.ref }}
      CHANGELOG: ${{ github.event.pull_request.body }}
      ENVIRONMENT: PROD
    secrets:
      TOKEN: ${{ secrets.DIPLO_BOT_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  send_ir_mail:
    name: Send Prod Release Email
    runs-on: ubuntu-latest
    needs: watch_for_deploy_status
    environment: PROD
    if: needs.watch_for_deploy_status.outputs.STATUS == 'success'
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ github.event.pull_request.title }}
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ vars.EMAIL_SENDER }}
          html_body: ${{ github.event.pull_request.body }}
          ignore_cert: true
          convert_markdown: true
          attachments: attachments.zip,git.diff,./dist/static/*.js
          priority: low
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}