name: Send Test Status Notification

on:
  workflow_call:
    inputs:
      TITLE:
        type: string
      REQUESTED:
        default: false
        type: boolean
      SUCCESS:
        default: false
        type: boolean
      FAIL:
        default: false
        type: boolean        
      BRANCH:
        default: ${{ github.event.pull_request.base.ref }}
        type: string
      ENVIRONMENT:
        type: string
        
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:        
  test_requested_notification:
    name: Send Tests Requested Slack Notification
    uses: ./.github/workflows/send_slack_notifications.yml
    if: ${{ inputs.REQUESTED }}
    with:
      TYPE: TESTS
      JOB_STATUS: Requested
      TITLE: ${{ inputs.TITLE }}
      GITHUB_USER: ${{ github.actor }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_BRANCH: ${{ inputs.BRANCH }}
      JOB_NO: ${{ github.run_number }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    secrets: inherit

  test_success_notification:
    name: Send Tests Success Slack Notification
    uses: ./.github/workflows/send_slack_notifications.yml
    if: ${{ inputs.SUCCESS }}
    with:
      TYPE: TESTS
      JOB_STATUS: Success
      TITLE: ${{ inputs.TITLE }}
      GITHUB_USER: ${{ github.actor }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_BRANCH: ${{ inputs.BRANCH }}
      JOB_NO: ${{ github.run_number }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    secrets: inherit
      
  test_failure_notification:
    name: Send Tests Failure Slack Notification
    uses: ./.github/workflows/send_slack_notifications.yml
    if: ${{ inputs.FAIL }}
    with:
      TYPE: TESTS
      JOB_STATUS: Failure
      TITLE: ${{ inputs.TITLE }}
      GITHUB_USER: ${{ github.actor }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_BRANCH: ${{ inputs.BRANCH }}
      JOB_NO: ${{ github.run_number }}
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    secrets: inherit
